### ISSUE TITLE
🚀 Set up CI/CD pipeline with GitHub Actions

### ISSUE THREAD

**Issue by jane-alesi** [satwareAG/qrcode-mcp#4]
# Set up CI/CD Pipeline

## Description
Implement automated CI/CD pipeline using GitHub Actions for testing, building, and deployment automation.

### Basic CI Pipeline
- [ ] Create `.github/workflows/ci.yml` for continuous integration
- [ ] Set up automated testing on push/PR
- [ ] Configure multiple Node.js versions testing (LTS, Current)
- [ ] Add code coverage reporting and upload to Codecov/Coveralls

### Code Quality Automation
- [ ] Integrate ESLint and Prettier checks
- [ ] Set up automatic dependency vulnerability scanning
- [ ] Add TypeScript type checking in CI
- [ ] Configure automated code quality gates

### Build and Release Automation
- [ ] Automate TypeScript compilation and build verification
- [ ] Set up automated npm package publishing (when ready)
- [ ] Create release workflow with changelog generation
- [ ] Add Docker image build and registry push

### Advanced Features
- [ ] Set up semantic versioning with conventional commits
- [ ] Configure automatic dependency updates (Dependabot)
- [ ] Add performance regression testing
- [ ] Set up deployment previews for documentation

## Workflow Structure
```yaml
name: CI/CD Pipeline
on: [push, pull_request]
jobs:
  test:      # Run tests and coverage
  lint:      # Code quality checks  
  build:     # Verify builds succeed
  release:   # Automated releases (main branch only)
```

## Acceptance Criteria
- All commits automatically tested
- Failed tests block merging to main
- Automated releases for version tags
- Code coverage visible on PRs
- Fast pipeline execution (< 5 minutes)

## Priority
🟡 **High** - Critical for development workflow automation

## Dependencies
- Depends on testing framework (#3) being implemented first
